version: '3'
services:
  sqlite_db:
    image: postgres:13
    container_name: postgres_db
    environment:
      SQLITE_DB_NAME: postgres
      SQLITE_USER: postgres
      SQLITE_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgressql/data

volumes:
  postgres_data: